@Basket_HostAddress = https://localhost:7066/basket

GET {{Basket_HostAddress}}/swn
Accept: application/json

###

POST {{Basket_HostAddress}}
content-type: application/json
{
  "UserName": "swn",
  "Items": [
    {
      "ProductId": 1,
      "Quantity": 2,
      "Color": "Red",
      "Price": 500.00,
      "ProductName": "Solar Powered Flashlight"
    },
    {
      "ProductId": 2,
      "Quantity": 1,
      "Color": "Blue",
      "Price": 500.00,
      "ProductName": "Hiking Poles"
    }
  ]
}

###

DELETE {{Basket_HostAddress}}/swn
content-type: application/json

###