@Basket_HostAddress = https://localhost:7066/basket

GET {{Basket_HostAddress}}/swn
Accept: application/json

###

POST {{Basket_HostAddress}}
content-type: application/json
{
  "UserName": "swn",
  "Items": [
    {
      "ProductId": 1,
      "Quantity": 2,
      "Color": "Red",
      "Price": 0,
      "ProductName": "Solar Powered Flashlight"
    },
    {
      "ProductId": 2,
      "Quantity": 1,
      "Color": "Blue",
      "Price": 0,
      "ProductName": "Hiking Poles"
    },
    {
      "ProductId": 9,
      "Quantity": 5,
      "Color": "Blue",
      "Price": 0,
      "ProductName": "Camping Tent"
    }
  ]
}

###

DELETE {{Basket_HostAddress}}/swn
content-type: application/json

###

POST http://localhost:8080/realms/GenericAI/protocol/openid-connect/token
content-type: application/x-www-form-urlencoded

grant_type=password&client_id=GenericAI-Client&scope=email openid&username=test&password=1234